version: "3.6"

services:
   mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"

volumes:
  mongodb: